### PR TITLE
fix: replace line2byte check

### LINKED ISSUE #238: Alpha screen no longer shown at startup on nvim head
I updated to neovim HEAD this morning (https://github.com/neovim/neovim/commit/bec13cfcafe73d33ed707b690fd924b1f52241f8), and realized that I no longer see the Alpha screen at startup.

On closer look, it seems like the default neovim screen is shown briefly and then an empty file is opened:

https://github.com/goolord/alpha-nvim/assets/159/19126f50-f931-4d03-bf84-6177334ed173

I realize the follies of HEAD, but figure on sharing in case it means something needs to be fixed in alpha or neovim.

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #238 

This solution is inspired from [`mini.starter`](https://github.com/echasnovski/mini.nvim/blob/a1b96721dea1e9c7aeeb4bd402b9debebf38ed23/lua/mini/starter.lua#L1408-L1431). Note how the comment there explains how @echasnovski had encountered a similar (?) issue using `line2byte` in the past.

### CODE REVIEW

**Comment by technicalpickles** [comment]
Fixes it for me 🎊 

I was curious if the line for `vim.fn.argc() >0 ` was needed from mini.starter, but I checked and it seems to correctly not show alpha when called like `nvim file_1.txt file_2.txt` etc

**Comment by goolord** [comment]
> I was curious if the line for vim.fn.argc() >0 was needed 

yes, that check already exists https://github.com/goolord/alpha-nvim/pull/239/files#diff-ec96159a0e4ab00d2629897381414ffd88f8e88aa0b82e2f8ba6e24da2873239R573

thank you for your contribution!

File: lua/alpha.lua [hunk 1]
```diff
@@ -572,8 +572,15 @@ local function should_skip_alpha()
     -- don't start when opening a file
     if vim.fn.argc() > 0 then return true end
 
-    -- skip stdin
-    if vim.fn.line2byte("$") ~= -1 then return true end
+    -- Do not open alpha if the current buffer has any lines (something opened explicitly).
+    local lines = vim.api.nvim_buf_get_lines(0, 0, -1, true)
+    if #lines > 1 or (#lines == 1 and lines[1]:len() > 0) then return true end
```
Comment (bew) [inline lua/alpha.lua:577]: Note: getting all the lines only to check if there are 1 or 2+ _could_ lead to perf issues if the file has many lines

Comment (MariaSolOs) [reply lua/alpha.lua:577]: Fixing it in #240.
